#! /usr/bin/env python


# Import necessary libraries for communication and display use
import drivers
from time import sleep
from datetime import datetime
import serial


display = drivers.Lcd()
ser = serial.Serial('/dev/ttyACM0')

try:
    print("Writing to display")
    while True:
        for ligne in ser:
                if "GNGNS" in ligne:
                        line = ligne.split(",")
                        display.lcd_display_string(line[2],1)
                        display.lcd_display_string(line[3],2)
                        sleep(5) 
                        display.lcd_clear()
                if "GNGNS" in ligne:
                        line = ligne.split(",")
                        display.lcd_display_string(line[-10],1)
                        display.lcd_display_string(line[-9],2)                           
                        sleep(5) 
                        display.lcd_clear()
        sleep(5)
except KeyboardInterrupt:
    # If there is a KeyboardInterrupt (when you press ctrl+c), exit the program and cleanup
    print("Cleaning up!")
    display.lcd_clear()
